services:
  cube:
    image: cubejs/cube:latest
    ports:
      - 4000:4000
      - 15432:15432
    environment:
      - CUBEJS_DEV_MODE=true
    volumes:
      - .:/cube/conf

  superset:
    image: apache/superset:latest
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_SECRET_KEY=your_secret_key_here
    volumes:
      - superset-data:/app/superset_home
      - ./dbt/ondoriya/data:/data # Mount your DuckDB file location
    command: >
      sh -c "superset fab create-admin --username admin --firstname Admin --lastname Admin --email admin@superset.com --password admin &&
            superset db upgrade &&
            superset init &&
            superset run -h 0.0.0.0 -p 8088"

  rabbitmq:
    image: rabbitmq:latest
    hostname: rabbitmq_server
    container_name: rabbitmq_container
    ports:
      - "5672:5672" # AMQP protocol port
      - "15672:15672" # RabbitMQ Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/ # Persistent storage for RabbitMQ data
      - rabbitmq_logs:/var/log/rabbitmq/ # Persistent storage for RabbitMQ logs
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=storage
      - MINIO_REGION_NAME=us-east-1
      - MINIO_REGION=us-east-1
    ports:
      - 9001:9001
      - 9000:9000
    command: ["server", "/data", "--console-address", ":9001"]
    volumes:
      - minio_data:/data
    networks:
      - default

volumes:
  superset-data:
  rabbitmq_data:
  rabbitmq_logs:
  minio_data:

networks:
  default:
