version: 2
sources:
  - name: bronze
    description: "Raw data files stored in MinIO bronze bucket"
    tables:
      - name: faction_distribution
        description: "Faction distribution data"
      - name: households
        description: "Household data"
      - name: language_building_blocks
        description: "Language building blocks data"
      - name: language_roots
        description: "Language roots data"
      - name: moons
        description: "Moon data"
      - name: people
        description: "People data"
      - name: planets
        description: "Planet data"
      - name: region_biome
        description: "Region biome data"
      - name: regions
        description: "Regions data"
  - name: silver
    description: "Cleaned and transformed data"
    tables:
      - name: silver_faction_distribution
      - name: silver_households
      - name: silver_language_building_blocks
      - name: silver_language_roots
      - name: silver_moons
      - name: silver_people
      - name: silver_planets
      - name: silver_region_biome
      - name: silver_regions
